# Generated by Django 4.2.4 on 2023-08-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_books_bname_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='Bname',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='Date',
        ),
        migrations.AddField(
            model_name='reader',
            name='Email',
            field=models.EmailField(default='D@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reader',
            name='Rid',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='Rname',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tdate', models.DateField()),
                ('Sdate', models.DateField()),
                ('Bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books')),
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
        ),
    ]
